[package]
name = "nag-driver"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
