[package]
name = "cargo-nag"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
color-eyre = "0.6.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
toml = "0.5.10"
